spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reuniones
    username: postgres
    password: RootRoot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
