INSERT INTO reunion (ID, ASUNTO, FECHA) VALUES (99, 'Reunión Navidad', CURRENT_TIMESTAMP);
INSERT INTO reunion (ID, ASUNTO, FECHA) VALUES (100, 'Reunión ayer', CURRENT_TIMESTAMP);
INSERT INTO reunion (ID, ASUNTO, FECHA) VALUES (101, 'Reunión mañana', CURRENT_TIMESTAMP);
